# Generated by Django 5.2.14 on 2026-05-12 20:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ingestion', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='ingestionrun',
            new_name='ingestion_i_source_5684b6_idx',
            old_name='ingestion_i_source__9dd2f8_idx',
        ),
    ]
