# Generated by Django 5.2.14 on 2026-05-12 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ingestion', '0002_rename_ingestion_i_source__9dd2f8_idx_ingestion_i_source_5684b6_idx'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingestionrun',
            name='status',
            field=models.CharField(choices=[('started', 'Started'), ('success', 'Success'), ('failed', 'Failed'), ('skipped', 'Skipped')], default='started', max_length=16),
        ),
    ]
