# Generated by Django 5.2.14 on 2026-05-12 20:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ml_models', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='modelrun',
            new_name='ml_models_m_model_f_311299_idx',
            old_name='ml_models_m_model_f_80ae5f_idx',
        ),
    ]
