# Generated by Django 5.2.14 on 2026-05-12 20:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rankings', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='dailyranking',
            new_name='rankings_da_date_fc2a08_idx',
            old_name='rankings_da_date_4135db_idx',
        ),
    ]
