# Generated by Django 5.2.14 on 2026-05-12 20:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('features', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='dailyfeature',
            new_name='features_da_feature_7f6645_idx',
            old_name='features_dai_feature_f0ff17_idx',
        ),
    ]
