# Generated by Django 5.2.14 on 2026-05-12 20:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('labels', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='predictionlabel',
            new_name='labels_pred_label_s_aa132a_idx',
            old_name='labels_pred_label_s_0e2dc0_idx',
        ),
    ]
